version: "3.8"
services:
  app:
    build: .
    ports: 
      - 5000:5000
    env_file: .env
    depends_on: 
      - postgres
    volumes:
      - ./:/app/
      - /app/node_modules
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: uchow
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
      - 5432:5432
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
  